apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/prod
    repoURL: https://github.com/thomsen883/bgd-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
